### ISSUE TITLE
Analog Mode Rx not working after Tx

### ISSUE THREAD

**Issue by onemikedelta** [tmiw/ezDV#27]
In analog mode audio routing is ok after device reset. Transmit is also ok. However, It is not routing back the radio audio to the user audio.
Used firmware: ezdv-20231122-full

**Comment by tmiw** [comment]
I believe https://github.com/tmiw/ezDV/commit/89552ddb52b05465ed2de981ccec28808de11187 will fix this based on my testing with SmartSDR and the Flex 6300 here. The issue was that there was logic missing to return to RX mode when in analog; I suspect if you push the Mode button after letting go of PTT to switch to e.g. 700D (and then go back to analog), RX will start working fine again.

Anyway, feel free to update here if it's still not solved after the next FW update and I'll reopen and investigate further.
